# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sales_pb2 as sales__pb2


class SalesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessSale = channel.unary_unary(
                '/SalesService/ProcessSale',
                request_serializer=sales__pb2.SalesMessage.SerializeToString,
                response_deserializer=sales__pb2.ConfirmationReply.FromString,
                )
        self.GetSalesStatistics = channel.unary_unary(
                '/SalesService/GetSalesStatistics',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sales__pb2.ConfirmationReply.FromString,
                )


class SalesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessSale': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSale,
                    request_deserializer=sales__pb2.SalesMessage.FromString,
                    response_serializer=sales__pb2.ConfirmationReply.SerializeToString,
            ),
            'GetSalesStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesStatistics,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sales__pb2.ConfirmationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SalesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SalesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalesService/ProcessSale',
            sales__pb2.SalesMessage.SerializeToString,
            sales__pb2.ConfirmationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSalesStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SalesService/GetSalesStatistics',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sales__pb2.ConfirmationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
